"""initial tables

Revision ID: beabfff9ced4
Revises: 
Create Date: 2026-03-25 13:42:35.667534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'beabfff9ced4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_hi', sa.Text(), nullable=True),
    sa.Column('text_mr', sa.Text(), nullable=True),
    sa.Column('bhava_tag', sa.String(length=50), nullable=False),
    sa.Column('bhava_description_en', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('preferred_locale', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_session_token'), 'assessments', ['session_token'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=20), nullable=False),
    sa.Column('answered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('sattva_yes', sa.Integer(), nullable=False),
    sa.Column('sattva_no', sa.Integer(), nullable=False),
    sa.Column('sattva_sometimes', sa.Integer(), nullable=False),
    sa.Column('rajas_yes', sa.Integer(), nullable=False),
    sa.Column('rajas_no', sa.Integer(), nullable=False),
    sa.Column('rajas_sometimes', sa.Integer(), nullable=False),
    sa.Column('tamas_yes', sa.Integer(), nullable=False),
    sa.Column('tamas_no', sa.Integer(), nullable=False),
    sa.Column('tamas_sometimes', sa.Integer(), nullable=False),
    sa.Column('sattva_primary_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rajas_primary_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tamas_primary_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sattva_secondary_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rajas_secondary_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tamas_secondary_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('primary_dominant_guna', sa.String(length=20), nullable=False),
    sa.Column('secondary_dominant_guna', sa.String(length=20), nullable=True),
    sa.Column('prakriti_type', sa.String(length=50), nullable=False),
    sa.Column('prakriti_subtype', sa.String(length=50), nullable=True),
    sa.Column('archetype_title', sa.String(length=100), nullable=True),
    sa.Column('sattva_bala', sa.String(length=20), nullable=False),
    sa.Column('ai_insights', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('answers')
    op.drop_index(op.f('ix_assessments_session_token'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
